version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    volumes:
      - mongodb_data:/data/db
    networks:
      - event-reward-network

  gateway:
    build:
      context: .
      dockerfile: ./packages/gateway/Dockerfile
    container_name: gateway
    ports:
      - "${GATEWAY_SERVER_PORT}:${GATEWAY_SERVER_PORT}"
    environment:
      - GATEWAY_PORT=${GATEWAY_SERVER_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - EVENT_SERVICE_URL=${EVENT_SERVICE_URL}
    depends_on:
      - auth
      - event
    networks:
      - event-reward-network

  auth:
    build:
      context: .
      dockerfile: ./packages/auth/Dockerfile
    container_name: auth
    ports:
      - "${AUTH_SERVER_PORT}:${AUTH_SERVER_PORT}"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongodb
    networks:
      - event-reward-network

  event:
    build:
      context: .
      dockerfile: ./packages/event/Dockerfile
    container_name: event
    ports:
      - "${EVENT_SERVER_PORT}:${EVENT_SERVER_PORT}"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongodb
    networks:
      - event-reward-network

networks:
  event-reward-network:
    driver: bridge

volumes:
  mongodb_data:
